"""
Public logging for the cross-sub ban bot.

Three artifacts:
  * public_ban_log.json  — append-only audit trail (every action)
  * public_ban_log.md    — last 30 days, newest first, GitHub-renderable
  * public_ban_log.html  — searchable table of last 200 actions, for GH Pages

The .md and .html views are only re-rendered when something was logged
this run (so 20-minute idle runs don't churn the repo).
"""

import os
import json
from datetime import datetime, timedelta
from html import escape

PUBLIC_LOG_JSON = "public_ban_log.json"
PUBLIC_EVENTS_JSON = "public_ban_events.json"
PUBLIC_LOG_MD = "public_ban_log.md"
PUBLIC_LOG_HTML = "public_ban_log.html"

RECENT_DAYS = 30
HTML_MAX_ROWS = 200
HTML_RECENT_DAYS = 7  # default-tab cutoff in the HTML dashboard

# Module-level flag: did this run actually log anything?
_logged_this_run = False


def log_public_action(action, username, subreddit, source_sub="", actor="Bot", note=""):
    """Append a single action to the public JSON log."""
    global _logged_this_run
    entry = {
        "timestamp": datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S'),
        "action": action,
        "username": username,
        "subreddit": subreddit,
        "source_sub": source_sub,
        "actor": actor,
        "note": note,
    }
    try:
        data = []
        if os.path.exists(PUBLIC_LOG_JSON):
            try:
                with open(PUBLIC_LOG_JSON, 'r') as f:
                    data = json.load(f)
            except json.JSONDecodeError:
                print(f"[WARN] {PUBLIC_LOG_JSON} unreadable, starting fresh.")
                data = []

        data.append(entry)
        with open(PUBLIC_LOG_JSON, 'w') as f:
            json.dump(data, f, indent=2)

        _logged_this_run = True
        print(f"[LOG] {action} u/{username} in r/{subreddit} (from {source_sub or 'n/a'})")

    except Exception as e:
        print(f"[ERROR] log_public_action failed: {e}")


def log_ban_event(action, moderator, user, source, propagated, total):
    """Append ONE row per ban/unban EVENT (not per propagation target).

    This is the permanent, human-readable audit record the dashboard reads:
      "joe BANNED bob (from r/leafs) -> 8/9 subs"
    The per-target public_ban_log.json stays as the short-lived propagation
    troubleshooting log; this one is the durable four-column event view
    (timestamp, moderator, user, source).
    """
    import os, json
    from datetime import datetime
    entry = {
        "timestamp": datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S'),
        "action": action,
        "moderator": moderator or "unknown",
        "user": user,
        "source": source,
        "propagated_to": propagated,
        "pact_subs": total,
    }
    try:
        data = []
        if os.path.exists(PUBLIC_EVENTS_JSON):
            try:
                with open(PUBLIC_EVENTS_JSON) as f:
                    data = json.load(f)
            except json.JSONDecodeError:
                data = []
        data.append(entry)
        with open(PUBLIC_EVENTS_JSON, 'w') as f:
            json.dump(data, f, indent=2)
        print(f"[EVENT] {moderator or 'unknown'} {action} u/{user} "
              f"(from {source}) -> {propagated}/{total} subs")
    except Exception as e:
        print(f"[ERROR] log_ban_event failed: {e}")


def flush_views():
    """Regenerate .md and .html if anything was logged this run."""
    if not _logged_this_run:
        return
    try:
        with open(PUBLIC_LOG_JSON, 'r') as f:
            entries = json.load(f)
    except Exception as e:
        print(f"[ERROR] flush_views: cannot read JSON: {e}")
        return

    # Sort once, newest first
    entries.sort(key=lambda e: e.get('timestamp', ''), reverse=True)

    # Recent slice for the markdown view
    cutoff_dt = datetime.utcnow() - timedelta(days=RECENT_DAYS)
    cutoff_s = cutoff_dt.strftime('%Y-%m-%d %H:%M:%S')
    recent = [e for e in entries if e.get('timestamp', '') >= cutoff_s]

    _write_markdown(recent, total=len(entries))
    _write_html(entries[:HTML_MAX_ROWS], total=len(entries))


def _write_markdown(recent, total):
    """Last-30-days view as a Markdown table."""
    try:
        with open(PUBLIC_LOG_MD, 'w') as f:
            f.write("# NHL Cross-Sub Ban Log — Recent Activity\n\n")
            f.write(f"_Auto-generated by the bot. Showing the last {RECENT_DAYS} days "
                    f"({len(recent)} of {total} total actions). "
                    f"Last updated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC._\n\n")
            f.write("Full audit trail: [`public_ban_log.json`](public_ban_log.json) · "
                    "Searchable view: [`public_ban_log.html`](public_ban_log.html)\n\n")

            if not recent:
                f.write(f"_No actions in the last {RECENT_DAYS} days._\n")
                return

            f.write("| Timestamp (UTC) | Action | User | Subreddit | Source | Actor |\n")
            f.write("|---|---|---|---|---|---|\n")
            _SYMBOLS = {
                'BANNED': '❌ BANNED',
                'UNBANNED': '✅ UNBANNED',
                'FORGIVEN': '🕊️ FORGIVEN',
            }
            for e in recent:
                action = e.get('action', '')
                symbol = _SYMBOLS.get(action, action or '—')
                f.write(
                    f"| {e.get('timestamp', '')} "
                    f"| {symbol} "
                    f"| u/{e.get('username', '')} "
                    f"| r/{e.get('subreddit', '')} "
                    f"| {e.get('source_sub', '') or '—'} "
                    f"| {e.get('actor', '') or '—'} |\n"
                )
    except Exception as e:
        print(f"[ERROR] _write_markdown: {e}")


def _write_html(rows, total):
    """Compact searchable table for GitHub Pages with Recent (7d) / All tabs."""
    try:
        last_updated = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
        cutoff_30d = (datetime.utcnow() - timedelta(days=RECENT_DAYS)).strftime('%Y-%m-%d %H:%M:%S')
        cutoff_7d = (datetime.utcnow() - timedelta(days=HTML_RECENT_DAYS)).strftime('%Y-%m-%d %H:%M:%S')

        recent_30d_count = sum(1 for e in rows if e.get('timestamp', '') >= cutoff_30d)
        bans_30d = sum(1 for e in rows if e.get('timestamp', '') >= cutoff_30d and e.get('action') == 'BANNED')
        unbans_30d = recent_30d_count - bans_30d
        recent_7d_count = sum(1 for e in rows if e.get('timestamp', '') >= cutoff_7d)

        body_rows = []
        for e in rows:
            action = e.get('action', '')
            cls = 'banned' if action == 'BANNED' else 'unbanned'
            ts = e.get('timestamp', '')
            is_recent = '1' if ts >= cutoff_7d else '0'
            body_rows.append(
                f'<tr class="{cls}" data-recent="{is_recent}">'
                f'<td>{escape(ts)}</td>'
                f'<td>{escape(action)}</td>'
                f'<td>u/{escape(e.get("username", ""))}</td>'
                f'<td>r/{escape(e.get("subreddit", ""))}</td>'
                f'<td>{escape(e.get("source_sub", "") or "—")}</td>'
                f'<td>{escape(e.get("actor", "") or "—")}</td>'
                f'</tr>'
            )

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>NHL Cross-Sub Ban Log</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
         max-width: 1100px; margin: 2rem auto; padding: 0 1rem;
         background: Canvas; color: CanvasText; }}
  h1 {{ margin: 0 0 .25rem; font-size: 1.4rem; }}
  .meta {{ color: #888; margin-bottom: 1.5rem; font-size: .9rem; }}
  .stats {{ display: flex; gap: 1.5rem; margin-bottom: 1rem; flex-wrap: wrap; }}
  .stat {{ background: rgba(127,127,127,.08); padding: .5rem 1rem; border-radius: 6px; }}
  .stat strong {{ display: block; font-size: 1.4rem; }}
  .tabs {{ display: flex; gap: .25rem; margin-bottom: .5rem; border-bottom: 1px solid rgba(127,127,127,.2); }}
  .tab {{ padding: .5rem .9rem; cursor: pointer; border: none; background: none;
         color: CanvasText; font: inherit; border-bottom: 2px solid transparent; }}
  .tab[aria-selected="true"] {{ border-bottom-color: #36c; font-weight: 600; }}
  .tab:hover {{ background: rgba(127,127,127,.06); }}
  input[type=search] {{ width: 100%; padding: .5rem .75rem; margin-bottom: 1rem;
                       border: 1px solid rgba(127,127,127,.3); border-radius: 6px;
                       background: Canvas; color: CanvasText; font: inherit; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  th, td {{ text-align: left; padding: .4rem .6rem;
           border-bottom: 1px solid rgba(127,127,127,.15); }}
  th {{ position: sticky; top: 0; background: Canvas; font-weight: 600; }}
  tr.banned td:nth-child(2) {{ color: #c33; }}
  tr.unbanned td:nth-child(2) {{ color: #2a8; }}
  tr.hidden {{ display: none; }}
  .empty {{ color: #888; text-align: center; padding: 1.5rem; }}
  .footer {{ color: #888; font-size: .85rem; margin-top: 1.5rem; }}
  a {{ color: #36c; }}
</style>
</head>
<body>
<h1>NHL Cross-Sub Ban Log</h1>
<div class="meta">Auto-generated. Last updated {last_updated}. Showing the last {len(rows)} of {total} total actions.</div>

<div class="stats">
  <div class="stat"><strong>{total}</strong>total actions</div>
  <div class="stat"><strong>{recent_7d_count}</strong>last 7 days</div>
  <div class="stat"><strong>{bans_30d}</strong>bans, last {RECENT_DAYS}d</div>
  <div class="stat"><strong>{unbans_30d}</strong>unbans, last {RECENT_DAYS}d</div>
</div>

<div class="tabs" role="tablist">
  <button class="tab" id="tab-recent" role="tab" aria-selected="true" aria-controls="rows">Recent ({HTML_RECENT_DAYS}d)</button>
  <button class="tab" id="tab-all" role="tab" aria-selected="false" aria-controls="rows">All ({len(rows)})</button>
</div>

<input id="filter" type="search" placeholder="Filter by user, subreddit, action, source…">

<table>
  <thead>
    <tr><th>Timestamp (UTC)</th><th>Action</th><th>User</th><th>Subreddit</th><th>Source</th><th>Actor</th></tr>
  </thead>
  <tbody id="rows">
    {''.join(body_rows) if body_rows else '<tr><td colspan="6" class="empty">No actions yet.</td></tr>'}
  </tbody>
</table>
<div id="empty-recent" class="empty" hidden>No actions in the last {HTML_RECENT_DAYS} days.</div>

<div class="footer">
  Full audit trail: <a href="public_ban_log.json">public_ban_log.json</a> ·
  Markdown view: <a href="public_ban_log.md">public_ban_log.md</a> ·
  <a href="https://github.com/re-verse/cross_sub_ban_bot">source</a>
</div>

<script>
  const input = document.getElementById('filter');
  const rows = document.querySelectorAll('#rows tr');
  const tabRecent = document.getElementById('tab-recent');
  const tabAll = document.getElementById('tab-all');
  const emptyRecent = document.getElementById('empty-recent');
  let scope = 'recent';

  function apply() {{
    const q = input.value.toLowerCase().trim();
    let shownInScope = 0;
    rows.forEach(r => {{
      const inScope = (scope === 'all') || r.dataset.recent === '1';
      const matchesQuery = !q || r.textContent.toLowerCase().includes(q);
      const show = inScope && matchesQuery;
      r.classList.toggle('hidden', !show);
      if (inScope) shownInScope++;
    }});
    if (emptyRecent) {{
      emptyRecent.hidden = !(scope === 'recent' && shownInScope === 0);
    }}
  }}

  function selectTab(which) {{
    scope = which;
    tabRecent.setAttribute('aria-selected', which === 'recent');
    tabAll.setAttribute('aria-selected', which === 'all');
    apply();
  }}

  tabRecent.addEventListener('click', () => selectTab('recent'));
  tabAll.addEventListener('click', () => selectTab('all'));
  input.addEventListener('input', apply);
  apply();
</script>
</body>
</html>
"""
        with open(PUBLIC_LOG_HTML, 'w') as f:
            f.write(html)
    except Exception as e:
        print(f"[ERROR] _write_html: {e}")
