- name: Debug secrets
  run: |
    echo "REDDIT_USERNAME=$REDDIT_USERNAME"
    echo "REDDIT_CLIENT_ID=$REDDIT_CLIENT_ID"
  env:
    REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
    REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
