name: Reddit API Connection Test

# Define triggers for the workflow (e.g., on push to main, or manually)
on:
  push:
    branches: [ main ] # Example: Run on pushes to the main branch
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  test-connection:
    runs-on: ubuntu-latest # Use a standard runner environment

    steps:
      # 1. Check out your repository code
      - name: Check out code
        uses: actions/checkout@v4 # Use the standard checkout action

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Specify your desired Python version

      # 3. Install Python dependencies (like praw)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw prawcore # Install libraries needed by your script

      # 4. Run your Python script
      - name: Run Reddit Connection Test Script
        env: # Pass secrets as environment variables to the script
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python reddit_test.py # Execute your Python file
