name: Reddit API Connection Test

# Define triggers for the workflow
on:
  push:
    branches: [ main ] # Example: Run on pushes to the main branch
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  test-connection:
    name: Test Reddit API Connection
    runs-on: ubuntu-latest # Use a standard runner environment

    steps:
      # 1. Check out your repository code
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify a stable Python version

      # 3. Install Python dependencies (praw and prawcore)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw prawcore # Ensure both are installed

      # 4. Run your Python script with CORRECT secret mapping
      - name: Run Reddit Connection Test Script
        env:
          # Map your actual GitHub Secret names (right side)
          # to the environment variables your script expects (left side)
          CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          USERNAME: ${{ secrets.REDDIT_USERNAME }}
          PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        run: python reddit_test.py # Make sure filename matches your script
