name: Reddit API Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw
      - name: Set environment variables
        run: |
          echo "CLIENT_ID=$REDDIT_CLIENT_ID" >> $GITHUB_ENV
          echo "CLIENT_SECRET=$REDDIT_CLIENT_SECRET" >> $GITHUB_ENV
          echo "USERNAME=$REDDIT_USERNAME" >> $GITHUB_ENV
          echo "PASSWORD=$REDDIT_PASSWORD" >> $GITHUB_ENV
        env:
          CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          USERNAME: ${{ secrets.REDDIT_USERNAME }}
          PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
      - name: Run Reddit API test
        run: python reddit_test.py
