name: Run Cross-Sub Ban Bot

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 min
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install praw gspread oauth2client

    - name: Decode service account key
      run: echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" | base64 -d > sa_credentials.json

    - name: Debug Reddit secrets
      run: |
        echo "CLIENT_ID: $CLIENT_ID"
        echo "USERNAME: $USERNAME"
      env:
        CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        USERNAME: ${{ secrets.REDDIT_USERNAME }}

    - name: Run bot
      run: python3 cross_sub_ban_bot.py
      env:
        CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        USERNAME: ${{ secrets.REDDIT_USERNAME }}
        PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}

    - name: Commit and push updated public ban log
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git fetch origin main
        git checkout main
        git add public_ban_log.md public_ban_log.json
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update public ban log"
          git push origin main
        fi
